using System.Text;
using ChatCRM.Domain.Entities;
using Microsoft.AspNetCore.Identity;

namespace ChatCRM.MVC.Services
{
    public class FileEmailSender : IEmailSender<User>
    {
        private readonly IWebHostEnvironment _environment;
        private readonly ILogger<FileEmailSender> _logger;

        public FileEmailSender(IWebHostEnvironment environment, ILogger<FileEmailSender> logger)
        {
            _environment = environment;
            _logger = logger;
        }

        public Task SendConfirmationLinkAsync(User user, string email, string confirmationLink)
        {
            return WriteEmailAsync(
                email,
                "Confirm your ChatCRM account",
                "Use the link below to verify your email address and finish setting up your account.",
                confirmationLink);
        }

        public Task SendPasswordResetLinkAsync(User user, string email, string resetLink)
        {
            return WriteEmailAsync(
                email,
                "Reset your ChatCRM password",
                "Use the link below to choose a new password for your account.",
                resetLink);
        }

        public Task SendPasswordResetCodeAsync(User user, string email, string resetCode)
        {
            return WriteEmailAsync(
                email,
                "Your ChatCRM password reset code",
                $"Use this code to reset your password: {resetCode}",
                null);
        }

        private async Task WriteEmailAsync(string email, string subject, string message, string? actionLink)
        {
            var emailDirectory = Path.Combine(_environment.ContentRootPath, "App_Data", "emails");
            Directory.CreateDirectory(emailDirectory);

            var safeEmail = string.Join("_", email.Split(Path.GetInvalidFileNameChars(), StringSplitOptions.RemoveEmptyEntries)).ToLowerInvariant();
            var fileName = $"{DateTime.UtcNow:yyyyMMddHHmmssfff}_{safeEmail}.html";
            var filePath = Path.Combine(emailDirectory, fileName);

            var builder = new StringBuilder();
            builder.AppendLine("<html><body style=\"font-family:Segoe UI, sans-serif; color:#1f2937;\">");
            builder.AppendLine($"<h2>{subject}</h2>");
            builder.AppendLine($"<p>{System.Net.WebUtility.HtmlEncode(message)}</p>");

            if (!string.IsNullOrWhiteSpace(actionLink))
            {
                var encodedLink = System.Net.WebUtility.HtmlEncode(actionLink);
                builder.AppendLine($"<p><a href=\"{encodedLink}\">{encodedLink}</a></p>");
            }

            builder.AppendLine("<p>This email was generated by the local development email sender.</p>");
            builder.AppendLine("</body></html>");

            await File.WriteAllTextAsync(filePath, builder.ToString());
            _logger.LogInformation("Development email saved to {EmailPath}", filePath);
        }
    }
}
